<?php

namespace Hap\SoporteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    public function getNProductosAction($id_categoria){
        $query = $this->getEntityManager()
            ->createQuery(
                  'Select count(p.nombreProducto) '
                . 'from HapSoporteBundle:Producto p '
                . ' where p.estatus=2 and p.estado=1 and '
                . ' p.categoria = :id')->setParameter('id', $id_categoria)->getResult();
        $a = array();
        $a['-1']='Selecciona una opción';
        if(count($query)> 0){
            for($i=1; $i <= $query[0][1]; $i++)
                $a[$i] = $i;
        }
        
        return $a;
    }
}
