hap_soporte_homepage:
    path:     /hello/{name}
    defaults: { _controller: HapSoporteBundle:Default:index }
    
_inventario:
    resource: "@HapSoporteBundle/Controller/InventarioController.php"
    type:     annotation
    prefix:   /
