home:
    resource: "@HapSoporteBundle/Controller/HomeController.php"
    type:     annotation
    prefix:   /

_inventario:
    resource: "@HapSoporteBundle/Controller/InventarioController.php"
    type:     annotation
    prefix:   /
    
_catg:
    resource: "@HapSoporteBundle/Controller/CategoriaController.php"
    type:     annotation
    prefix:   /
    
_prd:
    resource: "@HapSoporteBundle/Controller/ProductoController.php"
    type:     annotation
    prefix:   /
    
_solicitud:
    resource: "@HapSoporteBundle/Controller/SolicitudController.php"
    type:     annotation
    prefix:   /
