parameters:
#    hap_usuario.example.class: Hap\UsuarioBundle\Example

services:
#    hap_usuario.example:
#        class: %hap_usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
